name: build-and-deploy

on:
  # Automatically trigger it when detected changes in repo. Remove comments to enable
  push:
   branches: 
     [ main ]

  # Allow mannually trigger 
  workflow_dispatch:   

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER}}
          username: ${{secrets.AZURE_CONTAINER_REGISTRY_NAME_USERNAME}}
          password: ${{secrets.AZURE_CONTAINER_REGISTRY_NAME_PASSWORD}}

      # - name: Verify Docker login
      #   run: |
      #     docker info
      #     # Look for your registry host (for example, regcrwlgqvzfiltj5u.azurecr.io)
      #     docker info | grep -i "${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}"

      # Push build cache to registry along with image (different tags)
      - name: Build and push container image to Azure Container Registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/cli@v2
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${{ secrets.AZURE_CONTAINER_APP_NAME }} -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} --server ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME_USERNAME }} --password ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME_PASSWORD }}
            az containerapp update -n ${{ secrets.AZURE_CONTAINER_APP_NAME }} -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} --image ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
